name = "jkd-admin-api-worker"
main = "index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "yowaretemplate-platform-db"
database_id = "931be9df-48fe-43ef-8270-dda773b8f573"

[vars]
GITHUB_REPO = "twmeric/YowareTemplate"
MEDIA_BUCKET_NAME = "jkd-media-yowaretemplate"
MEDIA_PUBLIC_URL = "https://pub-1424891a0bc54b758dea83d25b65a5d9.r2.dev"

[[r2_buckets]]
bucket_name = "jkd-media-yowaretemplate"
binding = "MEDIA_BUCKET"

# Create secrets with:
#   wrangler secret put ADMIN_PASSWORD
#   wrangler secret put ADMIN_TOKEN_SECRET
#   wrangler secret put GITHUB_TOKEN
